version: '3.8'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword

  wordpress:
    image: wordpress:php8.2-fpm
    volumes:
      - public_html:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8082:80"  # phpMyAdmin container exposed on port 8082
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - public_html:/var/www/html
    depends_on:
      - wordpress

volumes:
  db_data:
  public_html:
